# Form implementation generated from reading ui file '.\templates\VentanaSalir.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventanaDeseaSalir(object):
    def setupUi(self, ventanaDeseaSalir):
        ventanaDeseaSalir.setObjectName("ventanaDeseaSalir")
        ventanaDeseaSalir.resize(278, 158)
        self.widget = QtWidgets.QWidget(parent=ventanaDeseaSalir)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 281, 161))
        self.widget.setObjectName("widget")
        self.lblDeseaSalir = QtWidgets.QLabel(parent=self.widget)
        self.lblDeseaSalir.setGeometry(QtCore.QRect(100, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblDeseaSalir.setFont(font)
        self.lblDeseaSalir.setObjectName("lblDeseaSalir")
        self.btnAceptar = QtWidgets.QPushButton(parent=self.widget)
        self.btnAceptar.setGeometry(QtCore.QRect(50, 90, 75, 23))
        self.btnAceptar.setObjectName("btnAceptar")
        self.btnCancelar = QtWidgets.QPushButton(parent=self.widget)
        self.btnCancelar.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(ventanaDeseaSalir)
        QtCore.QMetaObject.connectSlotsByName(ventanaDeseaSalir)

    def retranslateUi(self, ventanaDeseaSalir):
        _translate = QtCore.QCoreApplication.translate
        ventanaDeseaSalir.setWindowTitle(_translate("ventanaDeseaSalir", "Dialog"))
        self.lblDeseaSalir.setText(_translate("ventanaDeseaSalir", "¿Desea Salir?"))
        self.btnAceptar.setText(_translate("ventanaDeseaSalir", "Aceptar"))
        self.btnCancelar.setText(_translate("ventanaDeseaSalir", "Cancelar"))
