# Form implementation generated from reading ui file 'VentanaCalendario.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventanaCalendario(object):
    def setupUi(self, ventanaCalendario):
        ventanaCalendario.setObjectName("ventanaCalendario")
        ventanaCalendario.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        ventanaCalendario.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventanaCalendario.sizePolicy().hasHeightForWidth())
        ventanaCalendario.setSizePolicy(sizePolicy)
        ventanaCalendario.setMinimumSize(QtCore.QSize(400, 300))
        ventanaCalendario.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/calendar.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaCalendario.setWindowIcon(icon)
        ventanaCalendario.setModal(True)
        self.calendario = QtWidgets.QCalendarWidget(parent=ventanaCalendario)
        self.calendario.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.calendario.setObjectName("calendario")

        self.retranslateUi(ventanaCalendario)
        QtCore.QMetaObject.connectSlotsByName(ventanaCalendario)

    def retranslateUi(self, ventanaCalendario):
        _translate = QtCore.QCoreApplication.translate
        ventanaCalendario.setWindowTitle(_translate("ventanaCalendario", "Calendario"))
